name: TownyDiscordBridge
version: 1.0.0
main: me.wyzebb.TownyDiscordBridge.TownyDiscordBridge
api-version: '1.21'
author: Wyzebb
description: A simple plugin to bridge between Towny and DiscordSRV and provide lots of useful features

depend: [Towny, DiscordSRV]

commands:
  townydiscordbridge:
    description: Towny and Discord link plugin main command
    aliases: tdb
    usage: /townydiscordbridge <subcommand>

# TODO: Finish command and permission definitions

permissions:
  townydiscordbridge.admin:
    description: Gives access to all TownyDiscordBridge commands
    children:
      TownyDiscordBridge.Check.Role.AllLinked: true
      TownyDiscordBridge.Check.Role: true
      TownyDiscordBridge.Check.Role.CreateAllTownsAndNations: true
      TownyDiscordBridge.Check.TextChannel.AllTownsAndNations: true
      TownyDiscordBridge.Check.VoiceChannel.AllTownsAndNations: true
  townydiscordbridge.Player:
    description: Gives regular player general commands
    children:
      TownyDiscordBridge.Check.Role: true
  townydiscordbridge.Check.Role.AllLinked:
    description: Allows you to force run a check for discord roles of all players in a town or nation then adds or removes
    default: false
  townydiscordbridge.Check.Role:
    description: Allows you to force run a check for discord roles of a single player in a town or nation then adds or removes
    default: false
  townydiscordbridge.Check.Role.CreateAllTownsAndNations:
    description: Allows you to force run a check for discord roles of all players in a town or nation and creates them if needed
    default: false
  townydiscordbridge.Check.TextChannel.AllTownsAndNations:
    description: Allows you to force run a check for discord text channels of all players in a town or nation and creates them if needed
    default: false
  townydiscordbridge.Check.VoiceChannel.AllTownsAndNations:
    description: Allows you to force run a check for discord voice channels of all players in a town or nation and creates them if needed
    default: false